# Generated by Django 5.2 on 2025-05-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='imports/')),
                ('tipo', models.CharField(choices=[('producto_ofertado', 'Productos Ofertados'), ('producto_disponible', 'Productos Disponibles')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de Importación',
                'verbose_name_plural': 'Tareas de Importación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
