# Generated by Django 5.2 on 2025-05-15 02:13

import directorio.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[directorio.validators.validate_telefono_ecuador])),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True, validators=[directorio.validators.validate_telefono_ecuador])),
                ('email', models.EmailField(max_length=254, validators=[directorio.validators.validate_email_corporativo])),
                ('direccion', models.TextField(blank=True, null=True)),
                ('obserbacion', models.TextField(blank=True, null=True)),
                ('ingerencia', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=13, validators=[directorio.validators.validate_ruc_ecuatoriano])),
                ('email', models.EmailField(max_length=254, validators=[directorio.validators.validate_email_corporativo])),
                ('telefono', models.CharField(max_length=20, validators=[directorio.validators.validate_telefono_ecuador])),
                ('direccion', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='basic.ciudad')),
                ('tipo_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='basic.tipocliente')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='basic.zona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[directorio.validators.validate_ruc_ecuatoriano])),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion1', models.TextField()),
                ('direccion2', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254, validators=[directorio.validators.validate_email_corporativo])),
                ('telefono', models.CharField(max_length=20, validators=[directorio.validators.validate_telefono_ecuador])),
                ('tipo_primario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='basic.ciudad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='RelacionBlue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='directorio.cliente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='directorio.contacto')),
            ],
            options={
                'verbose_name': 'Relación Blue',
                'verbose_name_plural': 'Relaciones Blue',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, validators=[directorio.validators.validate_email_corporativo])),
                ('telefono', models.CharField(max_length=20, validators=[directorio.validators.validate_telefono_ecuador])),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='directorio.proveedor')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
