# Generated by Django 5.2 on 2025-05-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('envio', 'Envío'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('vencimiento', 'Vencimiento'), ('conversion', 'Conversión a Orden')], max_length=20, verbose_name='Acción')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Proforma',
                'verbose_name_plural': 'Historiales de Proforma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo_item', models.CharField(choices=[('producto_ofertado', 'Producto Ofertado'), ('producto_disponible', 'Producto Disponible'), ('inventario', 'Producto de Inventario'), ('personalizado', 'Ítem Personalizado')], max_length=25, verbose_name='Tipo de ítem')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ítem de Proforma',
                'verbose_name_plural': 'Ítems de Proforma',
                'ordering': ['proforma', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.IntegerField(unique=True, verbose_name='Año')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último número')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Secuencia de Proforma',
                'verbose_name_plural': 'Secuencias de Proforma',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dias_validez', models.IntegerField(default=30, verbose_name='Días de validez predeterminados')),
                ('porcentaje_impuesto_default', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Porcentaje de impuesto predeterminado')),
                ('texto_condiciones_pago', models.CharField(max_length=500, verbose_name='Texto de condiciones de pago')),
                ('texto_tiempo_entrega', models.CharField(max_length=500, verbose_name='Texto de tiempo de entrega')),
                ('notas_predeterminadas', models.TextField(blank=True, verbose_name='Notas predeterminadas')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar logo')),
                ('mostrar_descuento', models.BooleanField(default=True, verbose_name='Mostrar descuento')),
                ('mostrar_impuesto', models.BooleanField(default=True, verbose_name='Mostrar impuesto')),
                ('mostrar_codigos', models.BooleanField(default=True, verbose_name='Mostrar códigos')),
                ('formato_moneda', models.CharField(default='$', max_length=10, verbose_name='Formato de moneda')),
                ('decimales', models.IntegerField(default=2, verbose_name='Decimales a mostrar')),
                ('empresa_predeterminada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.empresaclc', verbose_name='Empresa predeterminada')),
            ],
            options={
                'verbose_name': 'Configuración de Proforma',
                'verbose_name_plural': 'Configuraciones de Proforma',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre descriptivo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('atencion_a', models.CharField(max_length=100, verbose_name='Atención a')),
                ('condiciones_pago', models.CharField(max_length=255, verbose_name='Condiciones de pago')),
                ('tiempo_entrega', models.CharField(max_length=255, verbose_name='Tiempo de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de impuesto')),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Orden')], default='borrador', max_length=20, verbose_name='Estado')),
                ('tiene_orden', models.BooleanField(default=False, verbose_name='Tiene orden de venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directorio.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.empresaclc', verbose_name='Empresa')),
                ('tipo_contratacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.tipocontratacion', verbose_name='Tipo de contratación')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
