# Generated by Django 5.2 on 2025-05-15 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0002_initial'),
        ('proformas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proformahistorial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='proformahistorial',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proformas.proforma', verbose_name='Proforma'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productoinventario', verbose_name='Producto de inventario'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='producto_disponible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productodisponible', verbose_name='Producto disponible'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='producto_ofertado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productoofertado', verbose_name='Producto ofertado'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proformas.proforma', verbose_name='Proforma'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.unidad', verbose_name='Unidad'),
        ),
    ]
