# Generated by Django 5.2 on 2025-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionproforma',
            name='porcentaje_impuesto_default',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Porcentaje de impuesto predeterminado'),
        ),
    ]
