# Generated by Django 5.2 on 2025-05-31 07:36

from django.db import migrations


def update_tax_percentage(apps, schema_editor):
    """Update existing ConfiguracionProforma records from 12% to 15%"""
    ConfiguracionProforma = apps.get_model('proformas', 'ConfiguracionProforma')
    ConfiguracionProforma.objects.filter(porcentaje_impuesto_default=12.0).update(porcentaje_impuesto_default=15.0)


def reverse_tax_percentage(apps, schema_editor):
    """Reverse the tax percentage update from 15% to 12%"""
    ConfiguracionProforma = apps.get_model('proformas', 'ConfiguracionProforma')
    ConfiguracionProforma.objects.filter(porcentaje_impuesto_default=15.0).update(porcentaje_impuesto_default=12.0)


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0003_update_default_tax_to_15'),
    ]

    operations = [
        migrations.RunPython(update_tax_percentage, reverse_tax_percentage),
    ]
