# Generated by Django 5.2 on 2025-05-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=10)),
                ('fecha_orden', models.DateField()),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventario.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'ordering': ('-fecha_orden',),
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('SHIPPED', 'Enviada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=10)),
                ('fecha_orden', models.DateField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('precio_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_venta', to='inventario.almacen')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_venta', to='inventario.cliente')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Venta',
                'ordering': ('-fecha_orden',),
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('punto_reorden', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.unidad')),
            ],
            options={
                'verbose_name': 'Producto de inventario',
                'verbose_name_plural': 'Productos de inventario',
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.almacen')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ('almacen', 'codigo'),
                'unique_together': {('almacen', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('USED', 'Utilizada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('tabla_referencia', models.CharField(choices=[('PO', 'Orden de Compra'), ('SO', 'Orden de Venta'), ('ADJ', 'Ajuste'), ('MAN', 'Manual')], max_length=4)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.productoinventario')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Reserva de Inventario',
                'verbose_name_plural': 'Reservas de Inventario',
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_pedida', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.ordenventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='inventario.productoinventario')),
            ],
            options={
                'verbose_name': 'Línea de Orden de Venta',
                'verbose_name_plural': 'Líneas de Orden de Venta',
                'unique_together': {('orden_venta', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_pedida', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_compra', to='inventario.productoinventario')),
            ],
            options={
                'verbose_name': 'Línea de Orden de Compra',
                'verbose_name_plural': 'Líneas de Orden de Compra',
                'unique_together': {('orden_compra', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_movimiento', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('TRANSFER', 'Traslado'), ('ADJUST', 'Ajuste')], max_length=8)),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('tabla_referencia', models.CharField(choices=[('PO', 'Orden de Compra'), ('SO', 'Orden de Venta'), ('ADJ', 'Ajuste'), ('MAN', 'Manual')], max_length=4)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.productoinventario')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'indexes': [models.Index(fields=['producto', 'creado_en'], name='inventario__product_cd995e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_reservada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.productoinventario')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'unique_together': {('producto', 'almacen', 'ubicacion')},
            },
        ),
    ]
