# Generated by Django 5.2 on 2025-06-01 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NombreEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código único de la entidad', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la entidad', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la entidad', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la entidad está activa')),
            ],
            options={
                'verbose_name': 'Nombre de Entidad',
                'verbose_name_plural': 'Nombres de Entidad',
                'db_table': 'fastinfo_nombre_entidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DatosInstitucionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ruc', models.CharField(help_text='RUC de la entidad (13 dígitos)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 dígitos', regex='^\\d{13}$')])),
                ('usuario', models.CharField(help_text='Usuario para acceso al sistema de la entidad', max_length=100)),
                ('contrasena', models.CharField(help_text='Contraseña para acceso (se almacena encriptada)', max_length=255)),
                ('correo', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 10 dígitos', regex='^[0-9]{9,10}$')])),
                ('representante', models.CharField(help_text='Nombre del representante de la entidad', max_length=200)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física de la entidad', null=True)),
                ('sitio_web', models.URLField(blank=True, help_text='Sitio web oficial de la entidad', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la entidad está activa')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización de datos')),
                ('nombre_entidad', models.ForeignKey(help_text='Nombre de la entidad', on_delete=django.db.models.deletion.PROTECT, related_name='datos_institucionales', to='fastinfo.nombreentidad')),
            ],
            options={
                'verbose_name': 'Datos Institucionales',
                'verbose_name_plural': 'Datos Institucionales',
                'db_table': 'fastinfo_datos_institucionales',
                'ordering': ['nombre_entidad__nombre', 'ruc'],
                'indexes': [models.Index(fields=['ruc'], name='fastinfo_da_ruc_edc4ee_idx'), models.Index(fields=['nombre_entidad', 'activo'], name='fastinfo_da_nombre__941e4a_idx'), models.Index(fields=['usuario'], name='fastinfo_da_usuario_a800f5_idx')],
            },
        ),
    ]
