# Generated by Django 5.2 on 2025-05-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=255, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documento de Producto Disponible',
                'verbose_name_plural': 'Documentos de Productos Disponibles',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=255, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documento de Producto Ofertado',
                'verbose_name_plural': 'Documentos de Productos Ofertados',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('factura', models.CharField(max_length=100, unique=True, verbose_name='Número de Factura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Historial de Compra',
                'verbose_name_plural': 'Historial de Compras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDeVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('factura', models.CharField(max_length=100, unique=True, verbose_name='Número de Factura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Historial de Venta',
                'verbose_name_plural': 'Historial de Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Imagen de Producto Disponible',
                'verbose_name_plural': 'Imágenes de Productos Disponibles',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenReferenciaProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Imagen de Referencia',
                'verbose_name_plural': 'Imágenes de Referencia',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('tz_oferta', models.IntegerField(default=0, verbose_name='TZ Oferta')),
                ('tz_demanda', models.IntegerField(default=0, verbose_name='TZ Demanda')),
                ('tz_inflacion', models.IntegerField(default=0, verbose_name='TZ Inflación')),
                ('tz_calidad', models.IntegerField(default=0, verbose_name='TZ Calidad')),
                ('tz_eficiencia', models.IntegerField(default=0, verbose_name='TZ Eficiencia')),
                ('tz_referencial', models.IntegerField(default=0, verbose_name='TZ Referencial')),
                ('costo_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Referencial')),
                ('precio_sie_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio SIE Referencial')),
                ('precio_sie_tipob', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio SIE Tipo B')),
                ('precio_venta_privado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Venta Privado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto Disponible',
                'verbose_name_plural': 'Productos Disponibles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('cudim', models.CharField(max_length=100, unique=True, verbose_name='CUDIM')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('especialidad_texto', models.CharField(blank=True, default='', max_length=255, verbose_name='Texto de Especialidad')),
                ('referencias', models.TextField(blank=True, verbose_name='Referencias')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto Ofertado',
                'verbose_name_plural': 'Productos Ofertados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
