# Generated by Django 5.2 on 2025-05-15 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        ('directorio', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoproductodisponible',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_producto_disponible_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='documentoproductoofertado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_producto_ofertado_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='basic.empresaclc', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='directorio.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historialdeventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='directorio.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historialdeventas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='basic.empresaclc', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_producto_disponible_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_producto_ofertado_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_disponibles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='basic.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='basic.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='basic.procedencia', verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='unidad_presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='basic.unidad', verbose_name='Unidad de Presentación'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_disponibles_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='producto_disponible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.productodisponible', verbose_name='Producto Disponible'),
        ),
        migrations.AddField(
            model_name='historialdeventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.productodisponible', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='productos.productodisponible', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='documentoproductodisponible',
            name='producto_disponible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='productos.productodisponible', verbose_name='Producto Disponible'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_ofertados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_ofertados', to='basic.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_ofertados', to='basic.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_ofertados_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_producto_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='productos.productoofertado', verbose_name='Producto Ofertado'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='producto_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.productoofertado', verbose_name='Producto Ofertado'),
        ),
        migrations.AddField(
            model_name='documentoproductoofertado',
            name='producto_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='productos.productoofertado', verbose_name='Producto Ofertado'),
        ),
        migrations.AddField(
            model_name='productsprice',
            name='producto_disponible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.productodisponible', verbose_name='Producto Disponible'),
        ),
    ]
