# Generated by Django 5.2 on 2025-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproductodisponible',
            name='documento',
            field=models.FileField(upload_to='productos/documentos/%Y/%m/%d/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentoproductoofertado',
            name='documento',
            field=models.FileField(upload_to='productos/documentos/%Y/%m/%d/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='imagenproductodisponible',
            name='imagen',
            field=models.FileField(upload_to='productos/imagenes/%Y/%m/%d/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen',
            field=models.FileField(upload_to='productos/imagenes/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
