# Generated by Django 5.2 on 2025-05-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_add_product_image'),
        ('productos', '0003_alter_documentoproductodisponible_documento_and_more'),
    ]

    operations = [
    ]
