# Generated by Django 5.2 on 2025-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_merge_20250519_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho'),
        ),
    ]
