# Generated by Django 5.2 on 2025-05-19 07:11

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_imagenproductodisponible_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='imagen_original',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta imagen original'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='imagen_thumbnail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta miniatura'),
        ),
        migrations.AddField(
            model_name='imagenproductodisponible',
            name='imagen_webp',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta WebP'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen_original',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta imagen original'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen_thumbnail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta miniatura'),
        ),
        migrations.AddField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen_webp',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta WebP'),
        ),
        migrations.AlterField(
            model_name='documentoproductodisponible',
            name='documento',
            field=models.FileField(upload_to=productos.models.upload_documento_producto_disponible, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentoproductoofertado',
            name='documento',
            field=models.FileField(upload_to=productos.models.upload_documento_producto_ofertado, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='imagenproductodisponible',
            name='imagen',
            field=models.FileField(upload_to=productos.models.upload_imagen_producto_disponible, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen',
            field=models.FileField(upload_to=productos.models.upload_imagen_producto_ofertado, verbose_name='Imagen'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
