# Generated by Django 5.2 on 2025-05-19 15:11

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_imagenproductodisponible_imagen_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenreferenciaproductoofertado',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=productos.models.upload_imagen_producto_ofertado, verbose_name='Imagen'),
        ),
    ]
