# Generated by Django 5.2 on 2025-05-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_imagenreferenciaproductoofertado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodisponible',
            name='id_producto_ofertado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='productos.productoofertado', verbose_name='Producto Ofertado'),
        ),
    ]
