# Generated by Django 5.2 on 2025-05-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('productos', '0009_make_procedencia_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodisponible',
            name='unidad_presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='basic.unidad', verbose_name='Unidad de Presentación'),
        ),
    ]
