# Generated by Django 5.2 on 2025-05-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('productos', '0010_make_unidad_presentacion_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodisponible',
            name='id_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_disponibles', to='basic.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='id_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='basic.marca', verbose_name='Marca'),
        ),
    ]
