# Generated by Django 5.2 on 2025-05-29 07:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        ('directorio', '0002_tagging'),
        ('productos', '0011_make_marca_optional_add_especialidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único del brief', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título del Brief')),
                ('origin', models.CharField(choices=[('telefono', 'Telefónico'), ('email', 'Correo Electrónico'), ('presencial', 'Visita Presencial'), ('whatsapp', 'WhatsApp'), ('web', 'Sitio Web'), ('referido', 'Referido'), ('redes', 'Redes Sociales')], max_length=20, verbose_name='Origen del Pedido')),
                ('description', models.TextField(verbose_name='Descripción del Pedido')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto')),
                ('tiempo_entrega', models.IntegerField(help_text='Tiempo de entrega en días', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo de Entrega (días)')),
                ('forma_pago', models.CharField(choices=[('contado', 'Contado'), ('credito_15', 'Crédito 15 días'), ('credito_30', 'Crédito 30 días'), ('credito_45', 'Crédito 45 días'), ('credito_60', 'Crédito 60 días'), ('credito_90', 'Crédito 90 días'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pago')),
                ('destino', models.CharField(choices=[('cot_cliente', 'Cotización a Cliente'), ('sol_proveedor', 'Solicitud a Proveedor'), ('orden_compra', 'Orden de Compra'), ('proforma', 'Proforma'), ('analisis', 'Análisis de Precios')], max_length=50, verbose_name='Destino del Brief')),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('processing', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones Internas')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='briefs/attachments/', verbose_name='Archivo Adjunto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Operador Asignado')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriefHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='brief.brief')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Brief',
                'verbose_name_plural': 'Historial de Briefs',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='BriefItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200, verbose_name='Nombre del Producto (según cliente)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('specifications', models.TextField(blank=True, verbose_name='Especificaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Estimado')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='brief.brief', verbose_name='Brief')),
                ('product_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productodisponible', verbose_name='Producto de Inventario')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.unidad', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Item de Brief',
                'verbose_name_plural': 'Items de Brief',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['code'], name='brief_brief_code_c2997c_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['estado', 'priority'], name='brief_brief_estado_dfaaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['client', 'fecha_emision'], name='brief_brief_client__31860d_idx'),
        ),
    ]
